Saiyam Name Card
COPS-CSOC-2022/CSOC22-Week0-namecards pull request #32
Opened 2022-05-25 21:50 UTC by SaiRev0

2022-06-02 08:27 UTC, debarati-06 requested changes

2022-06-02 08:27 UTC, debarati-06 commented on utils/contributors.js
> +        image: "/images/saiyam.png",
You have not added any image file. If you prefer to to add any images then remove the image path line from code.

2022-06-18 13:30 UTC, SaiRev0 commented
but i have uploaded a image also

2022-06-18 13:36 UTC, SaiRev0 commented
is it correct now??

2022-06-18 13:44 UTC, debarati-06 approved these changes
LGTM! Task completed 🎉

2022-06-18 13:45 UTC, debarati-06 commented
> but i have uploaded a image also

Earlier the image file was missing in added files

2022-06-18 13:45 UTC, debarati-06 commented
> is it correct now??

Yes it looks perfect now !

2022-10-08 18:03 UTC, closed without merging